server:
  port: 1299
#注册到eureka中，并显示ip
eureka:
  instance:
    prefer-ip-address: true
  client:
    serviceUrl:
      defaultZone: http://root:root@localhost:8761/eureka/
spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/ranxinlong/aigou-config.git
  application:
    name: AIGOU-CONFIG
  #application: AIGOU-CONFIG