server:
  port: 6969
spring:
  application:
    name: AIGOU-ZUUL
#注册到eureka中，并显示ip
eureka:
  instance:
    prefer-ip-address: true
  client:
    serviceUrl:
      defaultZone: http://root:root@localhost:8761/eureka/
zuul:
  ignoredServices: '*' #只能通过路由访问，不能使用服务名访问
  routes:
    plat:
      serviceId: AIGOU-PLAT
      path: /plat/**
  prefix: /services